### PR TITLE
fix(husky): added commit message check hook (nb: requires npm install)

### PR DESCRIPTION
**Pull request by kepkap**
fix(husky): added commit message check hook (nb: requires npm install)

now commit message should conform 
https://github.com/conventional-changelog/commitlint/#what-is-commitlint

proper commit message struct values are prerequisites to semantic version release plugin to properly detect release x.y.z numbers.

### CODE REVIEW

**Comment by vlkolmakov** [comment]
@kepkap Are you sure this is the only way to implement sem ver? How the bronx team handles it?

Anyway, please don't merge before my PR. Otherwise all my commit messages will be invalid.

**Comment by kepkap** [comment]
@vlkolmakov  no worries, this guard hook will be applied to future commits only. past commits are totally fine.

**Comment by vlkolmakov** [comment]
What about my question? How the bronx team handles it? Let's talk to James and/or @jasonprado? What do you think?

**Comment by kepkap** [comment]
Judging from the git log history, Bronx does not use commit message conventions. 

the pattern:
type(scope?): subject  #scope is optional; multiple scopes are supported (current delimiter options: "/", "\" and ",")

the semantic version plugin relies on commit convention in the following way:
  
fix(tollgate): will result version increment v1.0.0 -> v1.0.1
feat(tollgate): will result version increment v1.0.0 -> v1.1.0

mentioning word breaking will result version increment v1.0.0 -> v2.0.0

**Pull request merged**
