### PR TITLE
Feat/location redis postgres combined store

### PR DESCRIPTION
**Pull request by kepkap**
Guys, apologies for rather big PR. Many file movements refactoring had to happen. 

New evolvement of project struct:
1. internal/service folder is only for controllers. (TODO, next PR: rename to internal/controllers)  
2. svc folder for domain services. (here goes any business logic that involves multiple entities)

svc/location 
folder contains tracking location updates and storing it into redis, postgres, and publish to redis 
(pubsub helps to build loose-coupled distributed services, lets keep it for now even though it is not used, later decide if needs to be removed) 

main service here is Tracker.
it has pluggable handler mechanism, allowing to chose what we do with location and detected crossings.
  

current handlers implementation for location: persist-2-postgres, store-2-redis, publish-2-redis
current handlers implementation for detected crossing: persist-2-postgres, publish-2-redis

### CODE REVIEW

**Comment by kevinmichaelchen** [comment]
After this is merged, let's get one PR in that is just refactoring, no code changes

**Comment by kepkap** [comment]
> After this is merged, let's get one PR in that is just refactoring, no code changes

yes, we need refactoring namely for:
1. unify dom model data access function names. (these differ slightly, Insert/Persist, queryXX vs GetXX, etc )
2. rename Longitude Latitude to Lon Lat . there is also a mixture in naming across the codebase, lets be more concise. 
3. rename controllers folder
4. Merge omecrossdetect.go into omecmd to follow the omecmd.go approach
5. unify api/gen and omeapi internal/omeapi. maybe use idl (interface definition language) folder name. Need to discuss, but not fall into any holy wars on the topic - just pick-up the convention and move forward.


cc @vlkolmakov @kevinmichaelchen

**Comment by kevinmichaelchen** [comment]
My only strong opinions here are 1) using internal and pkg, and 2) having only one folder for OME's protobufs.

**Review by vlkolmakov — APPROVED** [review]

**Comment by vlkolmakov** [comment]
> My only strong opinions here are 1) using internal and pkg

IMHO. Both are unnecessary and don't convey any useful meaning. Especially `internal` used for the wrong purpose.

**Comment by kepkap** [comment]
> There's a visibility [argument](https://dave.cheney.net/2019/10/06/use-internal-packages-to-reduce-your-public-api-surface) to be made, but I guess it's more of a preference than a hill. I am in favor of de-cluttered root levels. It's similar to why our front end projects throw everything in a src folder.
> 
> MR looks fine for now. This is not a blocker

wow, never knew go compiler forces no-import internals. thought of it more like convention. Kevin, thanks  for sharing!

**Pull request merged**
